### ISSUE TITLE
Failed to open TCP connection to localhost:2480

### ISSUE THREAD

**Issue by lepepe** [topofocus/active-orient#22]
`rescue in block in connect': Failed to open TCP connection to localhost:2480 (Connection refused - connect(2) for "localhost" port 2480) (Errno::ECONNREFUSED)

**Comment by topofocus** [comment]
There is no database-server at localhost
Are you able to connect to the database with studio or the console?

**Comment by lepepe** [comment]
Yes, I'm able to connect with studio. I am using, ruby 2.3, rails 5 and docker-compose 3

This is my Dockerfile:   
```
FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /supply-chain
WORKDIR /supply-chain
ADD Gemfile /supply-chain/Gemfile
ADD Gemfile.lock /supply-chain/Gemfile.lock
RUN bundle install
ADD . /supply-chain
```
docker-compose.yml
```
version: '3'
services:
  orientdb:
    image: orientdb:latest
    ports:
      - "2480:2480"
      - "2424:2424"
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/supply-chain
    ports:
      - "3000:3000"
    depends_on:
      - orientdb
```
Rails container error:   
`
/usr/local/lib/ruby/2.3.0/net/http.rb:882:in rescue in block in connect: Failed to open TCP connection to localhost:2480 (Cannot assign requested address - connect(2) for "localhost" port 2480) (Errno::EADDRNOTAVAIL)
`

OrientDB Studio:   
![screen shot 2017-07-31 at 8 57 25 am](https://user-images.githubusercontent.com/12739553/28778669-5473e5ac-75ce-11e7-8d42-c7f0157ae49b.png)
